version: "3.3"

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile

    image: php74-fpm:7.4.33

    container_name: otnamphp

    restart: unless-stopped

    hostname: php

    environment:
      TZ: ${TZ}

    expose:
      - "9000"

    ports:
      - "${SSH_PORT}:22"

    volumes:

      - ${HOME}/web/otnam/web:/var/www/html

      - ${PWD}/php/php.ini:/usr/local/etc/php/php.ini

    networks:
      - otnam

  nginx:

    image: nginx:1.26-alpine

    container_name: otnamnginx

    restart: unless-stopped

    hostname: nginx

    depends_on:
      - php

    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"

    volumes:

      - ${HOME}/web/otnam/web:/var/www/html:ro

      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    networks:
      - otnam

  mariadb:

    image: mariadb:10.5.22

    container_name: otnamdb

    restart: unless-stopped

    environment:

      TZ: ${TZ}

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      MYSQL_DATABASE: ${MYSQL_DATABASE}

      MYSQL_USER: ${MYSQL_USER}

      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    command:

      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

    ports:

      - "${MYSQL_PORT}:3306"

    volumes:

      - ${HOME}/web/otname/database:/var/lib/mysql

      - ${PWD}/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf

    networks:

      - otnam

  phpmyadmin:

    image: phpmyadmin:5.2

    container_name: otnamphpmyadmin

    restart: unless-stopped

    depends_on:

      - mariadb

    ports:

      - "${PMA_PORT}:80"

    environment:

      PMA_HOST: mariadb

      PMA_PORT: 3306

    networks:

      - otnam

networks:

  otnam:

    driver: bridge
